config/routes.rb
FashionFight::Application.routes.draw do

  scope :api do 
    post 'contests/:id/comments' => 'contests#comment', as: :contest_comment_api
  end

  resources :contests, :only => [:index, :show]
  root 'contests#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :contest
  belongs_to :user

  def as_json(options={})
    {
      id: self.id,
      user_id: self.user_id, # <---- the new line in this method
      contest_id: self.contest_id,
      side: self.side,
      username: self.username,
      comment: self.comment
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base

  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['title LIKE ? OR body LIKE ?', search_condition, search_condition])
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_filter :authenticate_user!, :only => [:comment, :destroy_comment]

  def index
    @contests = Contest.all
  end

  def show
    @contest = Contest.find(params[:id])
  end

  def comment
    @contest = Contest.find(params[:id])
    new_comment = @contest.comments.build(comment_params)
    new_comment.user_id = current_user.id
    new_comment.username = current_user.name

    # Use the bang to be able to save new_comment as the new saved object and pass it to the json below.
    new_comment.save!
    render :json => new_comment.to_json, :status => 200
  end

  def destroy_comment
    @comment = Comment.where(
      :id => params[:comment_id],
      :contest_id => params[:contest_id]
    ).first

    # TODO: Destroy the comment
    @comment.destroy if @comment.user_id == current_user.id

    render :nothing => true, :status => 200
  end

private

  def comment_params
    params.permit(:side, :comment)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @tasks = Task.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def search
    @posts = Post.where(title: params[:search])
    # @posts = Post.where('title LIKE ? ' "%#{params[:search]}%")

    redirect_to root_path unless @posts.count > 0
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :date, :body, :title_search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contests/show.html.erb
<div class="row">
  <div class="large-8 columns large-centered">
    <a href="/">&lt; Back</a>
    <h3><%= @contest.title %></h3>

    <div class="showcase row">
      <div class="left-side large-6 columns">
        <%= image_tag @contest.left %>
      </div>
      <div class="right-side large-6 columns">
        <%= image_tag @contest.right %>
      </div>
    </div>

    <div class="comment-wall"></div>

    <div class="panel">
      <h3><%= current_user.name %> Cast Your Vote!</h3>
      <form class="new-comment">
        <label>Vote</label>
        <!--  <select name="side">
          <option value="">============Choose a Side============</option>
          <option value="left">Left Side</option>
          <option value="right">Right Side</option>
        </select> -->
        <input type="radio" name="side" value="left"/>Left Side
        <input type="radio" name="side" value="right"/>Right Side
        <label>Comment</label>
        <textarea name="comment"></textarea>

        <input type="submit" value="Vote and Comment!" />
      </form>
    </div>
  </div>
</div>




<div id="templates">
  <script class="comment" type="text/template">
    <div class="small-3 large-2 columns"><img src="http://placehold.it/50x50&text=[img]" /></div>
    <div class="small-9 large-10 columns">
      <b>{{ username }}</b> (chose <b>{{ side }}</b>):
      <p>{{ comment }}</p>
      <a class="delete" href="#">Delete Comment</a>
    </div>
  </script>

  <script class="vote-count" type="text/template">
    <h4>{{ count }} Vote(s)</h4>
  </script>
</div>


<% content_for :javascript do %>
<script type="text/javascript">

  /* *
   * Lesson Step: The Comment Wall View
   */
  var wall = new CommentWall([], {
    url: '<%= contest_comment_api_path @contest %>'
  });

  var wallView = new CommentWallView({
    collection: wall,
    el: '.comment-wall'
  });

  wall.add(<%= raw @contest.comments.to_json %>);
  console.log(<%= raw @contest.comments.to_json %>);

  /* *
   * Lesson Step: The New Comment Form
   */
  // The view that handles adding new comments
  var commentForm = new CommentInputView({
    collection: wall,
    el: 'form.new-comment'
  });


  /* *
   * Lesson Step: The Vote Count View
   */
  // Each of these views displays the numebr of votes for each side
  var leftVoteCount = new VoteCountView({
    side: 'left',
    collection: wall
  });
  var rightVoteCount = new VoteCountView({
    side: 'right',
    collection: wall
  });

  leftVoteCount.render();
  rightVoteCount.render();
  $('.showcase .left-side').append(leftVoteCount.el);
  $('.showcase .right-side').append(rightVoteCount.el);

</script>
<% end %>

app/views/home/welcome.html.erb
<div class="container">
  <h1>Life Goals</h1>

  <form class="new-task">
    <input name="task_name" type="text" placeholder="Type a new task here..." />
    <button>Add Task</button>
  </form>

  <div id="task-list"></div>
</div>


<% content_for :javascript do %>
	
	<%= render 'welcome.js' %>

<% end %>

app/views/layouts/_intel.html.erb
<script type="text/javascript">
	window.g = {
		<% if user_signed_in? %>
			user: <%= raw current_user.to_json %>
		<% end %>
	};
</script>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="/">Blurred Press</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider hide-for-small"></li>
      <li class="has-dropdown"><a href="#">Posts</a>

        <ul class="dropdown">
          <li><label>Choses Post</label></li>
          <% @posts.each do |post| %>
            <li><%= link_to "#{post.title}", post_path(post) %></li>
          <% end %>
        </ul>
      </li>
      <li class="divider"></li>
      <li class="has-form">
          <div class="row collapse">
            <%= form_tag(search_path) do %>
              <div class="small-8 columns">
                
                <!-- <input type="text" name="title_search"> -->
                <%= text_field_tag :search, params[:search] %>
              </div>
              <div class="small-4 columns">
                <!-- <a href="#" class="alert button">Search</a> -->
                <%#= button_to "Search", search_path(params[:title_search]), class: "alert button" %>
                <%#= f.submit 'Search', class: "alert button", method: :post %>
                <%= submit_tag "Search", :name => nil, class: "alert button" %> 
              </div>
            <% end %>
          </div>
      </li>
      <li class="divider show-for-small"></li>
      <li class="has-form">
        <%= link_to 'New Post', new_post_path, class: 'button' %>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/_server_intel.html.erb
<script type="text/javascript">
	var taskrb = <%= raw @tasks.to_json %>;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FashionFight</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>

<%= render 'layouts/intel' %>
<%= javascript_include_tag "application" %>
<%= yield :javascript %>
</body>
</html>

app/views/posts/_form.html.haml
.row
  .large-4.large-centered.columns
    = simple_form_for @post do |f|
      = f.input :title, label: 'Blog Post Title'
      = f.input :date
      = f.input :body, size: "80x100"
      = f.button :submit

app/views/posts/index.html.haml
%h1 My blog

.large-8.large-centered.columns
  - @posts.each do |post|
    .post-preview
      %h2= link_to(post.title, post)
      %p= post.body.truncate(75)

app/views/posts/search.html.erb
<% if @posts.count > 0 %>
	<ul>
	    <% @posts.each do |post| %>
	  <li><%= link_to post.title, 
	    :action => 'show', :id => post.id  %></li>
	  <% end %>
	</ul>
<% else %>
	<p>No posts were found. <%= link_to "Go Home", root_path %></p>
<% end %>

app/views/posts/show.html.haml
%p#notice= notice

%article
  %h1.title= @post.title

  %time{datetime: @post.date.to_s, pubdate: true}= @post.date.to_s(:short)

  .body= simple_format(@post.body)

= link_to 'Edit', edit_post_path(@post), class: 'button'
\|
= link_to 'Back', posts_path

app/views/pricing/index.html.haml
%div.large-12.columns
  %h1 Start your free 30 day trial!
  %h2 No credit card, contract, or brain required

%div.large-12.columns
  .container
    .large-4.columns
      .plan.personal
        %h3 Personal

        .price $9

        .hide-for-small= image_tag 'http://placehold.it/280x150'

        %ul
          %li 2 GB storage
          %li 30 uploads / month
          %li Unlimited downloads
          %li Email support

        .start-button Start trial
    
    .large-4.columns
      .plan.premium
        %h3 Premium

        .price $29

        .hide-for-small= image_tag 'http://placehold.it/280x150'

        %ul
          %li 5 GB storage
          %li 60 uploads / month
          %li Unlimited downloads
          %li Chat support

        .start-button Start trial

    .large-4.columns
      .plan.enterprise
        %h3 Enterprise

        .price $59

        .hide-for-small= image_tag 'http://placehold.it/280x150'

        %ul
          %li 500 GB storage
          %li Unlimited uploads
          %li Unlimited downloads
          %li Telepathic support

        .start-button Start trial